---
- name: Instalando o Apache no Debian
  apt:
   name: "{{item}}"
   state: present
  with_items:
   - apache2

- name: Iniciando o servico
  service:
   name: apache2
   status: started

- name: Alterando pagina inicial
  blockinfile:
   path: /var/www/html/index.html
   marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
   content: "INFRAESTRUTURA AGIL COM DEVOPS"
