---
- name: Usando o WHEN
  hosts: all
  tasks:
   - name: Testando se um arquivo existe
     command: "test -f /etc/profile.d/dexter"
     register: result
     ignore_errors: yes

   - name: Configurando uma variavel do sistema
     shell: echo "export DEXTER=/opt/dexter > /etc/profile.d/dexter"
     when: result.rc == 0
